### ISSUE TITLE
open texture.png: no such file or directory

### ISSUE THREAD

**Issue by adamsir** [icexin/gocraft#21]
Steps to reproduce

- `$> go get github.com/icexin/gocraft`
- `$> gocraft`

This error will occur
```
2021/08/09 13:11:54.654137 PlatformError: Cocoa: Failed to retrieve display name
2021/08/09 13:11:54.775420 open texture.png: no such file or directory
panic: open texture.png: no such file or directory

goroutine 21 [running]:
log.Panic(0x1400015df68, 0x1, 0x1)
	/usr/local/go/src/log/log.go:354 +0x98
main.run()
	/Users/sudosu/golang/pkg/mod/github.com/icexin/gocraft@v0.0.0-20200316023038-ac6afbcc707b/main.go:332 +0x1cc
github.com/faiface/mainthread.Run.func1(0x1054bf1f0, 0x140000b0000)
	/Users/sudosu/golang/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x28
created by github.com/faiface/mainthread.Run
	/Users/sudosu/golang/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0x9c
```

my go env background:
In my zsh config, I have $GOPATH defined only, because $GOROOT is optional(https://dave.cheney.net/2013/06/14/you-dont-need-to-set-goroot-really) - maybe this is the problem, I'm not a golang programmer, but those go env variables are pain..

**Comment by icexin** [comment]
You may refer #20

**Comment by adamsir** [comment]
Thanks :) i thought all resources are compiled into binary
